# Generated by Django 6.0.5 on 2026-05-31 04:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('active', 'Active'), ('finished', 'Finished')], default='lobby', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex value like #A1B2C3.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eliminated', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to='game.player')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to='game.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_time_remaining_ms', models.IntegerField(default=60000)),
                ('defender_time_remaining_ms', models.IntegerField(default=60000)),
                ('current_turn', models.CharField(choices=[('attacker', 'Attacker'), ('defender', 'Defender')], default='attacker', max_length=20)),
                ('attacker_score', models.IntegerField(default=0)),
                ('defender_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='game.game')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks_started', to='game.gameplayer')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenses_faced', to='game.gameplayer')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won', to='game.gameplayer')),
            ],
        ),
        migrations.CreateModel(
            name='BattleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked_to', models.CharField(choices=[('attacker', 'Attacker'), ('defender', 'Defender')], max_length=20)),
                ('answered_correctly', models.BooleanField(blank=True, null=True)),
                ('time_taken_ms', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_questions', to='game.battle')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_questions', to='game.question')),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares', to='game.game')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_squares', to='game.gameplayer')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='contested_square',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='game.square'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.topic'),
        ),
    ]
