# Generated by Django 6.0.5 on 2026-05-31 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_battlequestion_order_alter_square_col_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='attacker_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='battle',
            name='attacker_time_remaining_ms',
            field=models.IntegerField(default=60000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='battle',
            name='defender_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='battle',
            name='defender_time_remaining_ms',
            field=models.IntegerField(default=60000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
