# Generated by Django 6.0.5 on 2026-05-31 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_battle_attacker_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='turn_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
