# Generated by Django 6.0.5 on 2026-06-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_question_image_url_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
