# Generated by Django 6.0.5 on 2026-06-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, upload_to='questions/'),
        ),
    ]
